data:
  name: CinPatent-EN
  data_dir: datasets/CinPatent-EN/en_0.05
  lang: en
  model:
    emb_size: 300

model:
  name: AttentionXML
  path: model
  model:
    hidden_size: 256
    layers_num: 1
    linear_size: [256]
    dropout: 0.5
    emb_trainable: False
  train:
    batch_size: 32
    nb_epoch: 31
    swa_warmup: 10
  valid:
    batch_size: 32
  predict:
    batch_size: 32
